name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
      - .github/**
  pull_request:
    branches: [ "main" ]
    paths:
      - backend/**
      - .github/**

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'backend'

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'gcard'
        mysql root password: 'root'
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        JWT_SECRET: dev_test_key
        DATABASE_PASSWORD: root
        DATABASE_NAME: gcard
        API_KEY: ${{ secrets.API_KEY }}
    - name: Run maven test
      run: |
        mvn test
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: /backend/target/site/jacoco/jacoco.xml
